// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: history_read_service.proto

package peer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AgeRequest) Reset() {
	*x = AgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeRequest) ProtoMessage() {}

func (x *AgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeRequest.ProtoReflect.Descriptor instead.
func (*AgeRequest) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{1}
}

func (x *AgeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AgesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start  int32   `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End    int32   `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Order  *Order  `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	Filter *Filter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *AgesRequest) Reset() {
	*x = AgesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgesRequest) ProtoMessage() {}

func (x *AgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgesRequest.ProtoReflect.Descriptor instead.
func (*AgesRequest) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{2}
}

func (x *AgesRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *AgesRequest) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *AgesRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *AgesRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type StoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StoryRequest) Reset() {
	*x = StoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryRequest) ProtoMessage() {}

func (x *StoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryRequest.ProtoReflect.Descriptor instead.
func (*StoryRequest) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{3}
}

func (x *StoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgeNames []string `protobuf:"bytes,1,rep,name=ageNames,proto3" json:"ageNames,omitempty"`
	Start    int32    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End      int32    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Order    *Order   `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	Filter   *Filter  `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *StoriesRequest) Reset() {
	*x = StoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoriesRequest) ProtoMessage() {}

func (x *StoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoriesRequest.ProtoReflect.Descriptor instead.
func (*StoriesRequest) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{4}
}

func (x *StoriesRequest) GetAgeNames() []string {
	if x != nil {
		return x.AgeNames
	}
	return nil
}

func (x *StoriesRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *StoriesRequest) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *StoriesRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *StoriesRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type AnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{5}
}

func (x *AnswerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AnswersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostableId string  `protobuf:"bytes,1,opt,name=postableId,proto3" json:"postableId,omitempty"`
	Start      int32   `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End        int32   `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Depth      int32   `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	Order      *Order  `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	Filter     *Filter `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"` // Add other fields as needed
}

func (x *AnswersRequest) Reset() {
	*x = AnswersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswersRequest) ProtoMessage() {}

func (x *AnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswersRequest.ProtoReflect.Descriptor instead.
func (*AnswersRequest) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{6}
}

func (x *AnswersRequest) GetPostableId() string {
	if x != nil {
		return x.PostableId
	}
	return ""
}

func (x *AnswersRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *AnswersRequest) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *AnswersRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *AnswersRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *AnswersRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// ~~~ Request Utilities ~~~
type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rule string `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{7}
}

func (x *Order) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Find   string `protobuf:"bytes,1,opt,name=find,proto3" json:"find,omitempty"`
	Reject string `protobuf:"bytes,2,opt,name=reject,proto3" json:"reject,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{8}
}

func (x *Filter) GetFind() string {
	if x != nil {
		return x.Find
	}
	return ""
}

func (x *Filter) GetReject() string {
	if x != nil {
		return x.Reject
	}
	return ""
}

type UserIdentity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username     string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ParentServer string `protobuf:"bytes,2,opt,name=parentServer,proto3" json:"parentServer,omitempty"`
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{9}
}

func (x *UserIdentity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserIdentity) GetParentServer() string {
	if x != nil {
		return x.ParentServer
	}
	return ""
}

type UserPublicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User      *UserIdentity `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	BirthDate int64         `protobuf:"varint,2,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	AboutMe   string        `protobuf:"bytes,3,opt,name=aboutMe,proto3" json:"aboutMe,omitempty"`
}

func (x *UserPublicInfo) Reset() {
	*x = UserPublicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPublicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPublicInfo) ProtoMessage() {}

func (x *UserPublicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPublicInfo.ProtoReflect.Descriptor instead.
func (*UserPublicInfo) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{10}
}

func (x *UserPublicInfo) GetUser() *UserIdentity {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserPublicInfo) GetBirthDate() int64 {
	if x != nil {
		return x.BirthDate
	}
	return 0
}

func (x *UserPublicInfo) GetAboutMe() string {
	if x != nil {
		return x.AboutMe
	}
	return ""
}

type Story struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string      `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	AgeName     string      `protobuf:"bytes,2,opt,name=ageName,proto3" json:"ageName,omitempty"`
	HistoryName string      `protobuf:"bytes,3,opt,name=historyName,proto3" json:"historyName,omitempty"`
	Postable    *Postable   `protobuf:"bytes,4,opt,name=postable,proto3" json:"postable,omitempty"`
	Answerable  *Answerable `protobuf:"bytes,5,opt,name=answerable,proto3" json:"answerable,omitempty"`
}

func (x *Story) Reset() {
	*x = Story{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Story) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Story) ProtoMessage() {}

func (x *Story) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Story.ProtoReflect.Descriptor instead.
func (*Story) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{11}
}

func (x *Story) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Story) GetAgeName() string {
	if x != nil {
		return x.AgeName
	}
	return ""
}

func (x *Story) GetHistoryName() string {
	if x != nil {
		return x.HistoryName
	}
	return ""
}

func (x *Story) GetPostable() *Postable {
	if x != nil {
		return x.Postable
	}
	return nil
}

func (x *Story) GetAnswerable() *Answerable {
	if x != nil {
		return x.Answerable
	}
	return nil
}

type Postable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Author    *UserIdentity `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Content   string        `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp int64         `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Postable) Reset() {
	*x = Postable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Postable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Postable) ProtoMessage() {}

func (x *Postable) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Postable.ProtoReflect.Descriptor instead.
func (*Postable) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{12}
}

func (x *Postable) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Postable) GetAuthor() *UserIdentity {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Postable) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Postable) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Answerable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*Answer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *Answerable) Reset() {
	*x = Answerable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Answerable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answerable) ProtoMessage() {}

func (x *Answerable) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answerable.ProtoReflect.Descriptor instead.
func (*Answerable) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{13}
}

func (x *Answerable) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type Answer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentId   string      `protobuf:"bytes,1,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Postable   *Postable   `protobuf:"bytes,2,opt,name=postable,proto3" json:"postable,omitempty"`
	Answerable *Answerable `protobuf:"bytes,3,opt,name=answerable,proto3" json:"answerable,omitempty"`
}

func (x *Answer) Reset() {
	*x = Answer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{14}
}

func (x *Answer) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Answer) GetPostable() *Postable {
	if x != nil {
		return x.Postable
	}
	return nil
}

func (x *Answer) GetAnswerable() *Answerable {
	if x != nil {
		return x.Answerable
	}
	return nil
}

type Age struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Owner       *UserIdentity `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	History     string        `protobuf:"bytes,4,opt,name=history,proto3" json:"history,omitempty"`
}

func (x *Age) Reset() {
	*x = Age{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Age) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Age) ProtoMessage() {}

func (x *Age) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Age.ProtoReflect.Descriptor instead.
func (*Age) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{15}
}

func (x *Age) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Age) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Age) GetOwner() *UserIdentity {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Age) GetHistory() string {
	if x != nil {
		return x.History
	}
	return ""
}

type AgeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ages []*Age `protobuf:"bytes,1,rep,name=ages,proto3" json:"ages,omitempty"`
}

func (x *AgeList) Reset() {
	*x = AgeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeList) ProtoMessage() {}

func (x *AgeList) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeList.ProtoReflect.Descriptor instead.
func (*AgeList) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{16}
}

func (x *AgeList) GetAges() []*Age {
	if x != nil {
		return x.Ages
	}
	return nil
}

type StoryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stories []*Story `protobuf:"bytes,1,rep,name=stories,proto3" json:"stories,omitempty"`
}

func (x *StoryList) Reset() {
	*x = StoryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryList) ProtoMessage() {}

func (x *StoryList) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryList.ProtoReflect.Descriptor instead.
func (*StoryList) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{17}
}

func (x *StoryList) GetStories() []*Story {
	if x != nil {
		return x.Stories
	}
	return nil
}

type AnswerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*Answer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *AnswerList) Reset() {
	*x = AnswerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_history_read_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerList) ProtoMessage() {}

func (x *AnswerList) ProtoReflect() protoreflect.Message {
	mi := &file_history_read_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerList.ProtoReflect.Descriptor instead.
func (*AnswerList) Descriptor() ([]byte, []int) {
	return file_history_read_service_proto_rawDescGZIP(), []int{18}
}

func (x *AnswerList) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

var File_history_read_service_proto protoreflect.FileDescriptor

var file_history_read_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x65,
	0x65, 0x72, 0x22, 0x29, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x20, 0x0a,
	0x0a, 0x41, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x7e, 0x0a, 0x0b, 0x41, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x65, 0x65, 0x72,
	0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22,
	0x1e, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x9d, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x21, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x65, 0x65, 0x72,
	0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22,
	0x1f, 0x0a, 0x0d, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0xb7, 0x01, 0x0a, 0x0e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64,
	0x65, 0x70, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65, 0x70, 0x74,
	0x68, 0x12, 0x21, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x1b, 0x0a, 0x05, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x22, 0x34, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x4e, 0x0a,
	0x0c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x70, 0x0a,
	0x0e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x26, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x65, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68,
	0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74,
	0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x4d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x22,
	0xb7, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x65, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65,
	0x65, 0x72, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x0a, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x7e, 0x0a, 0x08, 0x50, 0x6f, 0x73,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x34, 0x0a, 0x0a, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x22,
	0x82, 0x01, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x22, 0x7f, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x28, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x68,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x28, 0x0a, 0x07, 0x41, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x04, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x65, 0x52, 0x04, 0x61, 0x67, 0x65, 0x73, 0x22,
	0x32, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x07,
	0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x65, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x0a, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x26, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x32, 0xe4, 0x02, 0x0a, 0x12, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x32, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x70, 0x65,
	0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x12, 0x10,
	0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x09, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x41, 0x67, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x41, 0x67,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x65, 0x65, 0x72,
	0x2e, 0x41, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x33, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x65, 0x65, 0x72,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70,
	0x65, 0x65, 0x72, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x14, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b,
	0x61, 0x63, 0x70, 0x65, 0x6b, 0x77, 0x61, 0x73, 0x6e, 0x79, 0x2f, 0x6e, 0x6f, 0x75, 0x6e, 0x64,
	0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_history_read_service_proto_rawDescOnce sync.Once
	file_history_read_service_proto_rawDescData = file_history_read_service_proto_rawDesc
)

func file_history_read_service_proto_rawDescGZIP() []byte {
	file_history_read_service_proto_rawDescOnce.Do(func() {
		file_history_read_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_history_read_service_proto_rawDescData)
	})
	return file_history_read_service_proto_rawDescData
}

var file_history_read_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_history_read_service_proto_goTypes = []interface{}{
	(*UserRequest)(nil),    // 0: peer.UserRequest
	(*AgeRequest)(nil),     // 1: peer.AgeRequest
	(*AgesRequest)(nil),    // 2: peer.AgesRequest
	(*StoryRequest)(nil),   // 3: peer.StoryRequest
	(*StoriesRequest)(nil), // 4: peer.StoriesRequest
	(*AnswerRequest)(nil),  // 5: peer.AnswerRequest
	(*AnswersRequest)(nil), // 6: peer.AnswersRequest
	(*Order)(nil),          // 7: peer.Order
	(*Filter)(nil),         // 8: peer.Filter
	(*UserIdentity)(nil),   // 9: peer.UserIdentity
	(*UserPublicInfo)(nil), // 10: peer.UserPublicInfo
	(*Story)(nil),          // 11: peer.Story
	(*Postable)(nil),       // 12: peer.Postable
	(*Answerable)(nil),     // 13: peer.Answerable
	(*Answer)(nil),         // 14: peer.Answer
	(*Age)(nil),            // 15: peer.Age
	(*AgeList)(nil),        // 16: peer.AgeList
	(*StoryList)(nil),      // 17: peer.StoryList
	(*AnswerList)(nil),     // 18: peer.AnswerList
}
var file_history_read_service_proto_depIdxs = []int32{
	7,  // 0: peer.AgesRequest.order:type_name -> peer.Order
	8,  // 1: peer.AgesRequest.filter:type_name -> peer.Filter
	7,  // 2: peer.StoriesRequest.order:type_name -> peer.Order
	8,  // 3: peer.StoriesRequest.filter:type_name -> peer.Filter
	7,  // 4: peer.AnswersRequest.order:type_name -> peer.Order
	8,  // 5: peer.AnswersRequest.filter:type_name -> peer.Filter
	9,  // 6: peer.UserPublicInfo.user:type_name -> peer.UserIdentity
	12, // 7: peer.Story.postable:type_name -> peer.Postable
	13, // 8: peer.Story.answerable:type_name -> peer.Answerable
	9,  // 9: peer.Postable.author:type_name -> peer.UserIdentity
	14, // 10: peer.Answerable.answers:type_name -> peer.Answer
	12, // 11: peer.Answer.postable:type_name -> peer.Postable
	13, // 12: peer.Answer.answerable:type_name -> peer.Answerable
	9,  // 13: peer.Age.owner:type_name -> peer.UserIdentity
	15, // 14: peer.AgeList.ages:type_name -> peer.Age
	11, // 15: peer.StoryList.stories:type_name -> peer.Story
	14, // 16: peer.AnswerList.answers:type_name -> peer.Answer
	0,  // 17: peer.HistoryReadService.GetUser:input_type -> peer.UserRequest
	1,  // 18: peer.HistoryReadService.GetAge:input_type -> peer.AgeRequest
	2,  // 19: peer.HistoryReadService.GetAges:input_type -> peer.AgesRequest
	3,  // 20: peer.HistoryReadService.GetStory:input_type -> peer.StoryRequest
	4,  // 21: peer.HistoryReadService.GetStories:input_type -> peer.StoriesRequest
	5,  // 22: peer.HistoryReadService.GetAnswer:input_type -> peer.AnswerRequest
	6,  // 23: peer.HistoryReadService.GetAnswers:input_type -> peer.AnswersRequest
	10, // 24: peer.HistoryReadService.GetUser:output_type -> peer.UserPublicInfo
	15, // 25: peer.HistoryReadService.GetAge:output_type -> peer.Age
	16, // 26: peer.HistoryReadService.GetAges:output_type -> peer.AgeList
	11, // 27: peer.HistoryReadService.GetStory:output_type -> peer.Story
	17, // 28: peer.HistoryReadService.GetStories:output_type -> peer.StoryList
	14, // 29: peer.HistoryReadService.GetAnswer:output_type -> peer.Answer
	18, // 30: peer.HistoryReadService.GetAnswers:output_type -> peer.AnswerList
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_history_read_service_proto_init() }
func file_history_read_service_proto_init() {
	if File_history_read_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_history_read_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIdentity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPublicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Story); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Postable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Answerable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Answer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Age); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_history_read_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_history_read_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_history_read_service_proto_goTypes,
		DependencyIndexes: file_history_read_service_proto_depIdxs,
		MessageInfos:      file_history_read_service_proto_msgTypes,
	}.Build()
	File_history_read_service_proto = out.File
	file_history_read_service_proto_rawDesc = nil
	file_history_read_service_proto_goTypes = nil
	file_history_read_service_proto_depIdxs = nil
}
